import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import './style.css'
import Nav from './nav/page'
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BIS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        <Toaster />
        </body>
    </html>
  )
}
